
name: Build and Release Linux

on:
  push:
    # branches:
    #   master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: |
          go get .

      - name: Install robotgo dependencies
        run: |
          make install_linux_deps
        
      - name: Build on linux
        run: |
          make build_linux
          
      - name: Cross-compile for Windows
        run: |
          make build_windows

      - name: Release package
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gorobot-build-test-linux
            gorobot-build-test-windows.exe
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
