name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: make install_golang_deps

      - name: Install robotgo dependencies
        run: make install_linux_deps

      - name: Build Linux binary
        run: make build_linux

      - name: Build Windows binary
        run: make build_windows

      - name: Release package
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            robotgo-build-test-linux
            robotgo-build-test-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_test_darwin:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: make install_golang_deps

      - name: Build Darwin binary
        run: make build_darwin

      - name: Release package
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            robotgo-build-test-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
